name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  build-and-test:
    name: Build and Test Project
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js 20 and install pnpm
      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      # Step 3: Install dependencies
      - name: Install dependencies
        run: pnpm install

      # Step 4: Build the project
      - name: Build project
        run: pnpm build
        env:
          NODE_ENV: production

      # Step 5: Run tests
      - name: Run tests
        run: pnpm test

      # Optional: Upload build artifacts (dist folder)
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/
